image: ubuntu:latest

test:
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 setup.py install
  - python3 -m unittest discover -v
  - echo OK
